name: Build CAHighFPS Rootless
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/theos/theos:latest
      env:
        THEOS_PACKAGE_SCHEME: rootless
    steps:
      - uses: actions/checkout@v4

      - name: Build tweak
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          path: packages/*.deb
